# Все пользовательские тексты для admin_cons храним отдельно от логики.
admin_cons_text = {
    'access_denied': 'You do not have access to this command',
    'message_not_available': 'Message is not available',
    'list_title': 'Active consultation bookings:\nPage {page}',
    'empty': 'No active bookings',
    'no_name': 'No name',
    'next_page': 'Next page',
    'confirm': 'Confirm',
    'delete': 'Delete',
    'back_to_list': 'Back to list',
    'booking_not_found': 'Booking not found',
    'booking_not_active': 'This booking is no longer active',
    'booking_confirmed': 'Booking confirmed',
    'booking_deleted': 'Booking deleted',
    'card_title': 'Booking #{id}',
    'name': 'Name',
    'phone': 'Phone',
    'user_id': 'User ID',
    'date': 'Date',
    'time': 'Time',
    'status': 'Status',
    'events_title': 'Active important events:',
    'events_empty': 'No active important events',
    'add_event': '➕ Добавить событие',
    'delete_event': '🗑 Удалить',
    'back_to_events': 'Back to events',
    'event_not_found': 'Event not found',
    'event_deleted': 'Event deleted',
    'event_added': 'Событие добавлено',
    'event_title_step': 'Введите title события',
    'event_date_step': 'Введите event_date в формате YYYY-MM-DD',
    'event_date_error': 'Нужен формат даты YYYY-MM-DD',
    'event_description_step': 'Введите description события',
    'event_link_step': 'Введите link или /skip',
    'event_button_text_step': 'Введите button_text или /skip',
    'event_confirm_step': 'Проверьте событие перед публикацией',
    'event_publish': '✅ Опубликовать',
    'event_cancel': '❌ Отмена',
    'event_publish_canceled': 'Публикация события отменена',
}


booking_confirmed_user_text = {
    'RU': 'Ваша запись подтверждена администрацией',
    'EN': 'Your booking has been confirmed by the administration',
    'KY': 'Сиздин жазууңуз администрация тарабынан ырасталды',
}
